//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.7
//
package com.amazonaws.mobile;

import com.amazonaws.regions.Regions;

/**
 * This class defines constants for the developer's resource
 * identifiers and API keys. It should be kept private.
 */
public class AWSConfiguration {

    // AWS MobileHub user agent string
    public static final String AWS_MOBILEHUB_USER_AGENT =
        "MobileHub 8a5d1be7-8c49-482e-a7b1-51215aa37c2d aws-my-sample-app-android-v0.7";
    // AMAZON COGNITO
    public static final Regions AMAZON_COGNITO_REGION =
        Regions.US_EAST_1;
    public static final String  AMAZON_COGNITO_IDENTITY_POOL_ID =
        "us-east-1:c3719a72-d633-4f52-b6fc-ba9e8f595fc8";
    public static final String  AMAZON_COGNITO_USER_POOL_ID =
            "us-east-1_Czaq5p6hZ";
    public static final String  AMAZON_COGNITO_USER_POOL_CLIENT_ID =
            "7bl0qi82arcu87eetrpis9m53l";
    public static final String  AMAZON_COGNITO_USER_POOL_CLIENT_SECRET =
            "1u6cajq2af5baumshcmcnsrlqaofbbos80rmb2sb1vpns10o2a1i";
    // AMAZON MOBILE ANALYTICS
    public static final String  AMAZON_MOBILE_ANALYTICS_APP_ID =
        "f73fe10c00264069ad2802d5ecacc490";
    // Amazon Mobile Analytics region
    public static final Regions AMAZON_MOBILE_ANALYTICS_REGION = Regions.US_EAST_1;
    // GOOGLE CLOUD MESSAGING API KEY
    public static final String GOOGLE_CLOUD_MESSAGING_API_KEY =
        "AIzaSyByB9VuRrvTlxWCC5XhmmRbxN3Fuv4WBeg";
    // GOOGLE CLOUD MESSAGING SENDER ID
    public static final String GOOGLE_CLOUD_MESSAGING_SENDER_ID =
        "56852862438";

    // SNS PLATFORM APPLICATION ARN
    public static final String AMAZON_SNS_PLATFORM_APPLICATION_ARN =
        "arn:aws:sns:us-east-1:259919839452:app/GCM/airbridge_MOBILEHUB_6683380";
    // SNS DEFAULT TOPIC ARN
    public static final String AMAZON_SNS_DEFAULT_TOPIC_ARN =
        "arn:aws:sns:us-east-1:259919839452:airbridge_alldevices_MOBILEHUB_6683380";
    // SNS PLATFORM TOPIC ARNS
    public static final String[] AMAZON_SNS_TOPIC_ARNS =
        {};
    // S3 BUCKET
    public static final String AMAZON_S3_USER_FILES_BUCKET =
        "airbridge-userfiles-mobilehub-6683380";
}
